USE game460;


DROP TABLE IF EXISTS game_state;

CREATE TABLE IF NOT EXISTS game_state(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(16) NOT NULL DEFAULT "Phil", 
	status INT UNSIGNED DEFAULT 0,
	x_pos INT UNSIGNED DEFAULT 1,
	y_pos INT UNSIGNED DEFAULT 1,
	last_x INT UNSIGNED DEFAULT 0,
	last_y INT UNSIGNED DEFAULT 0,
	action INT UNSIGNED DEFAULT 0,
	other_id INT UNSIGNED DEFAULT 0,
	CONSTRAINT unique_id_constr UNIQUE(id)
);
