CREATE DATABASE IF NOT EXISTS game460;
USE game460;
GRANT EXECUTE ON game460.* TO 'root'@'localhost' IDENTIFIED BY 'jjsdatabase321';

-- table for Capture the Flag
DROP TABLE IF EXISTS game_state;
CREATE TABLE IF NOT EXISTS game_state(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(128) NOT NULL, 
	x_pos INT NOT NULL,
	y_pos INT NOT NULL,
	score INT UNSIGNED NOT NULL DEFAULT 0,
	has_flag INT UNSIGNED NOT NULL DEFAULT 0,
	is_alive INT UNSIGNED NOT NULL DEFAULT 1,
	CONSTRAINT unique_id UNIQUE(id),
	CONSTRAINT unique_name UNIQUE(name)
);
